"""initial

Revision ID: 9273444dc53c
Revises: 
Create Date: 2025-09-07 13:57:55.912373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9273444dc53c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('city', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('city', 'additional_info',
               existing_type=sa.VARCHAR(length=511),
               nullable=False)
    op.drop_index(op.f('ix_city_id'), table_name='city')
    op.drop_constraint(None, 'temperature', type_='foreignkey')
    op.create_foreign_key(None, 'temperature', 'city', ['city_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'temperature', type_='foreignkey')
    op.create_foreign_key(None, 'temperature', 'city', ['city_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_city_id'), 'city', ['id'], unique=1)
    op.alter_column('city', 'additional_info',
               existing_type=sa.VARCHAR(length=511),
               nullable=True)
    op.alter_column('city', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
